#!/bin/bash
echo "enter the name to check"
read name
if [ -f $name ]
then
echo "$name is a file"
cat $name
wc -l $name
elif [ -d $name ]
then
echo "$name is a directory"
find . -maxdepth 1 -type f
else
echo "$name is doesn't exist"
fi
