#!/bin/bash
num=0
while read line
do
words=`echo "$line"|wc -w`
num=`expr $num + 1`
char=`echo "$line"|awk '{print length}'`
echo "line number $num: number of words $words: number of characters $char"
done < $1
