#!/bin/bash
set -x
if [ $# -ne 1 ]
then
echo "pass one the input argument"
exit
fi
num=$1
fact=1
while [ $num -gt 1 ]
do
fact=`expr $fact \* $num`
num=`expr $num  - 1`
done
echo " factorial of given $1 number is $fact"

